language: python
python:
  # - "3.8"
  # - "3.9"
  # - "3.10" # Travis fails to install Python 3.10
  - "nightly"  # nightly build

install:
  - pip install -r requirements.txt

script:
  - cd docs
  - make html
