site_name: Gems
theme:
  name: material
nav:
    - Home: index.md
    - Python:
      - Design Patterns: python/design-patterns/index.md
      - Test Driven Development (TDD): python/tdd/index.md
      - Kata: python/kata/index.md
      - Tricks: python/tricks/index.md
      - Misc Python Topics: python/misc/index.md
    - Other:
      - SQL Server: sqlserver/index.md
    - Blog: blog/index.md
markdown_extensions:
  # Standard markdown extensions: https://python-markdown.github.io/sitemap.html
  - admonition
  - abbr
  - footnotes
  - attr_list
  - meta
  # pymdown extensions
  # pip install pymdown-extensions
  - pymdownx.keys  # https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
         - name: mermaid # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_div_format
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
#plugins:
#  # pip install mkdocs-plugin-mermaid
#  - markdownmermaid
 
 